ENT.Base 			= "npc_vj_bmce_undead_wlk_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Undead Female Office Worker Walker"
ENT.Author 			= "Pyri"
ENT.Contact 		= ""
ENT.Purpose 		= "Braaaainnns?"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "BMCE - Undead"