local White = Color(255, 100, 0)
killicon.Add("weapon_vj_bmce_degal", "vgui/wep/degal",White)
killicon.Add("weapon_vj_bmce_glock17", "vgui/wep/glock",White)
killicon.Add("weapon_vj_bmce_m9", "vgui/wep/m9",White)
killicon.Add("weapon_vj_bmce_357", "vgui/wep/357",White)
killicon.Add("weapon_vj_bmce_shotgun", "vgui/wep/shotgun",White)
killicon.Add("weapon_vj_bmce_spas12", "vgui/wep/spas12",White)
killicon.Add("weapon_vj_bmce_m4", "vgui/wep/m4a1",White)
killicon.Add("weapon_vj_bmce_mp5", "vgui/wep/mp5",White)